### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by vibOnTop** [eai04191/circle-hack#2]
im kinda confused on how to get this working, you should provide instructions.

**Comment by eai04191** [comment]
Simple steps:
1. install node 18
1. install yarn 1
1. Install dependencies with `yarn install`
1. Run with `yarn profit`

That's basically it. Some additional steps may be required depending on your environment.

By the way, this is a joke I made in an hour, for people with some knowledge to laugh. Running it will not produce more than the images and videos in this repo.
Therefore, I will not write a more detailed introduction. Thank you for your interest.

**Comment by vibOnTop** [comment]
ty, and sorry for long reply aswell
